# Generated by Django 5.1 on 2024-09-01 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=60)),
                ('Class_year', models.CharField(default='Unknown', max_length=20)),
                ('Exam_pattern', models.CharField(default='Unknown', max_length=15)),
                ('Question_paper', models.FileField(upload_to='Question_Paper', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Exam_Month', models.CharField(default='Unknown', max_length=10)),
                ('Exam_Year', models.CharField(default='2000', max_length=4)),
                ('Upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Uploader', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='AllQuestionPaper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
