# Generated by Django 5.1 on 2024-09-01 18:51

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_date', models.DateField(default=django.utils.timezone.now)),
                ('question', ckeditor.fields.RichTextField(max_length=6000)),
                ('q_likes', models.ManyToManyField(blank=True, related_name='self_q_likes', to=settings.AUTH_USER_MODEL)),
                ('q_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field_Q_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(default=django.utils.timezone.now)),
                ('answer', ckeditor.fields.RichTextField()),
                ('a_likes', models.ManyToManyField(blank=True, related_name='self_a_likes', to=settings.AUTH_USER_MODEL)),
                ('a_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_answer', to=settings.AUTH_USER_MODEL)),
                ('parent_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Users_QA.field_q')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='global', max_length=30)),
                ('logo_filed', models.ImageField(default='category_default.png', upload_to='Category_logo')),
                ('about_field', models.CharField(default='tap the button to see question(s).', max_length=230)),
                ('field_likes', models.ManyToManyField(blank=True, related_name='field_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='field_q',
            name='parent_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questions', to='Users_QA.fieldcategory'),
        ),
    ]
