# Generated by Django 5.1 on 2024-09-01 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users_action', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(verbose_name=1000)),
                ('comment_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply', models.TextField(verbose_name=1000)),
                ('comment_reply_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_model', to='Users_feeds.comment')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMemories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_tag', models.CharField(max_length=40)),
                ('Add_note', models.TextField(verbose_name=1500)),
                ('Add_file', models.FileField(upload_to='VirtualMemory', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])])),
                ('feed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_action.profile')),
                ('feed_likes', models.ManyToManyField(blank=True, related_name='feed_post_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_model', to='Users_feeds.virtualmemories'),
        ),
    ]
