# Generated by Django 5.1 on 2024-09-01 18:51

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactPerson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(default='Student', max_length=50)),
                ('user_image', models.ImageField(default='d304cd17231971fad58cab69d27a7e4eace197d7My_profile.jpg', help_text='500x500 is best.', upload_to='profile_pics')),
                ('user_resume', models.FileField(blank=True, help_text='only docx and doc files allowed.', null=True, upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc'])])),
                ('date_join', models.DateField(default=django.utils.timezone.now)),
                ('Web_url', models.CharField(blank=True, default='#', max_length=120)),
                ('Github_url', models.CharField(blank=True, default='#', max_length=120)),
                ('Linkedin_url', models.CharField(blank=True, default='#', max_length=120)),
                ('Insta_url', models.CharField(blank=True, default='#', max_length=120)),
                ('Fb_url', models.CharField(blank=True, default='#', max_length=120)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('follow', models.ManyToManyField(blank=True, related_name='follwers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=120, null=True)),
                ('body', models.TextField()),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250, null=True)),
                ('project_journey', ckeditor.fields.RichTextField()),
                ('projects_author', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
